import type { AppState, Gift, NotificationItem, Room, Transaction, User, VipPlan } from '../types/app';

const now = () => new Date().toISOString();
const ago = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();

export const seedUsers: User[] = [
  {
    id: 'user-zain',
    name: 'Zain Tahir',
    handle: 'zain',
    avatar: 'assets/avatar-zain.png',
    cover: 'assets/room-aurora.png',
    bio: 'Building a warmer internet, one voice room at a time.',
    followers: ['user-sana', 'user-ray', 'user-noor'],
    following: ['user-sana', 'user-ray'],
    level: 18,
    vipTier: 'Glow',
    coins: 4200,
    earnings: 1840,
    popularity: 92,
    activity: 78,
    blocked: false,
    badges: ['Founder', 'Host', 'Early VIP'],
    interests: ['Music', 'Gaming', 'Campus Talks'],
    joinedAt: ago(20_000),
  },
  {
    id: 'user-sana',
    name: 'Sana Mir',
    handle: 'sana.live',
    avatar: 'assets/avatar-sana.png',
    cover: 'assets/room-sunset.png',
    bio: 'Late-night stories, good playlists, and kind rooms.',
    followers: ['user-zain', 'user-ray', 'user-ali', 'user-maya'],
    following: ['user-zain', 'user-noor'],
    level: 31,
    vipTier: 'Prime',
    coins: 1800,
    earnings: 9600,
    popularity: 98,
    activity: 88,
    blocked: false,
    badges: ['Top Host', 'VIP Prime', 'Storyteller'],
    interests: ['Stories', 'Singing', 'Advice'],
    joinedAt: ago(60_000),
  },
  {
    id: 'user-ray',
    name: 'Ray Malik',
    handle: 'raybeats',
    avatar: 'assets/avatar-ray.png',
    cover: 'assets/room-cyber.png',
    bio: 'Beat battles and mini games after midnight.',
    followers: ['user-zain', 'user-noor', 'user-maya'],
    following: ['user-zain', 'user-sana'],
    level: 24,
    vipTier: 'Glow',
    coins: 2500,
    earnings: 5200,
    popularity: 84,
    activity: 94,
    blocked: false,
    badges: ['Game Master', 'DJ'],
    interests: ['Mini Games', 'Rap', 'Tech'],
    joinedAt: ago(43_000),
  },
  {
    id: 'user-noor',
    name: 'Noor Fatima',
    handle: 'noor.space',
    avatar: 'assets/avatar-noor.png',
    cover: 'assets/room-garden.png',
    bio: 'Study rooms, calm discussions, and daily motivation.',
    followers: ['user-zain', 'user-sana', 'user-ray'],
    following: ['user-zain', 'user-ali'],
    level: 16,
    vipTier: 'Free',
    coins: 950,
    earnings: 2100,
    popularity: 79,
    activity: 82,
    blocked: false,
    badges: ['Study Host'],
    interests: ['Study', 'Wellness', 'Community'],
    joinedAt: ago(23_000),
  },
  {
    id: 'user-ali',
    name: 'Ali Khan',
    handle: 'ali.vibes',
    avatar: 'assets/avatar-ali.png',
    cover: 'assets/room-midnight.png',
    bio: 'Open mic host. Bring a song or a good question.',
    followers: ['user-sana', 'user-noor'],
    following: ['user-sana', 'user-maya'],
    level: 12,
    vipTier: 'Free',
    coins: 620,
    earnings: 1450,
    popularity: 68,
    activity: 73,
    blocked: false,
    badges: ['Open Mic'],
    interests: ['Open Mic', 'Poetry', 'Friends'],
    joinedAt: ago(11_000),
  },
  {
    id: 'user-maya',
    name: 'Maya Riaz',
    handle: 'maya.arcade',
    avatar: 'assets/avatar-maya.png',
    cover: 'assets/room-cyber.png',
    bio: 'Runs quick games and party rooms.',
    followers: ['user-ray', 'user-ali'],
    following: ['user-ray', 'user-sana'],
    level: 14,
    vipTier: 'Glow',
    coins: 1200,
    earnings: 2400,
    popularity: 71,
    activity: 86,
    blocked: false,
    badges: ['Arcade Host'],
    interests: ['Games', 'Trivia', 'Hangouts'],
    joinedAt: ago(9_000),
  },
];

export const seedGifts: Gift[] = [
  { id: 'gift-spark', name: 'Spark', label: 'SP', price: 25, accent: '#3bebc2', rewardPoints: 5 },
  { id: 'gift-starwave', name: 'Starwave', label: 'SW', price: 80, accent: '#ffd561', rewardPoints: 18 },
  { id: 'gift-rosebeat', name: 'Rose Beat', label: 'RB', price: 140, accent: '#ff6e62', rewardPoints: 32 },
  { id: 'gift-crowncast', name: 'Crown Cast', label: 'CC', price: 300, accent: '#7d5cff', rewardPoints: 72 },
  { id: 'gift-aurora', name: 'Aurora Drop', label: 'AD', price: 720, accent: '#03c4ed', rewardPoints: 180 },
];

const roomMessages = [
  { id: 'rm-1', userId: 'user-sana', name: 'Sana Mir', body: 'Welcome in. Keep mics clean and vibes kind.', time: ago(24), kind: 'system' as const },
  { id: 'rm-2', userId: 'user-ray', name: 'Ray Malik', body: 'The next song prompt is ready.', time: ago(18), kind: 'chat' as const },
  { id: 'rm-3', userId: 'user-noor', name: 'Noor Fatima', body: 'I sent a Spark to the host.', time: ago(9), kind: 'gift' as const },
];

export const seedRooms: Room[] = [
  {
    id: 'room-afterglow',
    title: 'Afterglow Lounge',
    topic: 'Music',
    language: 'Urdu / English',
    hostId: 'user-sana',
    hostName: 'Sana Mir',
    cover: 'assets/room-sunset.png',
    mood: 'Chill',
    description: 'A soft live room for songs, stories, and relaxed conversation.',
    tags: ['Music', 'Stories', 'Late Night'],
    participants: [
      { userId: 'user-sana', name: 'Sana Mir', avatar: 'assets/avatar-sana.png', role: 'host', muted: false, speaking: true, vipTier: 'Prime' },
      { userId: 'user-ray', name: 'Ray Malik', avatar: 'assets/avatar-ray.png', role: 'speaker', muted: false, speaking: false, vipTier: 'Glow' },
      { userId: 'user-noor', name: 'Noor Fatima', avatar: 'assets/avatar-noor.png', role: 'listener', muted: true, speaking: false, vipTier: 'Free' },
      { userId: 'user-ali', name: 'Ali Khan', avatar: 'assets/avatar-ali.png', role: 'speaker', muted: true, speaking: false, vipTier: 'Free' },
    ],
    capacity: 18,
    live: true,
    locked: false,
    giftsReceived: 3820,
    raisedHands: ['user-noor'],
    messages: roomMessages,
    startedAt: ago(63),
  },
  {
    id: 'room-pulse',
    title: 'Pulse Arcade',
    topic: 'Mini Games',
    language: 'English',
    hostId: 'user-ray',
    hostName: 'Ray Malik',
    cover: 'assets/room-cyber.png',
    mood: 'Hype',
    description: 'Quick party games, beat challenges, and friendly leaderboard runs.',
    tags: ['Games', 'Arcade', 'Rewards'],
    participants: [
      { userId: 'user-ray', name: 'Ray Malik', avatar: 'assets/avatar-ray.png', role: 'host', muted: false, speaking: true, vipTier: 'Glow' },
      { userId: 'user-maya', name: 'Maya Riaz', avatar: 'assets/avatar-maya.png', role: 'moderator', muted: false, speaking: false, vipTier: 'Glow' },
      { userId: 'user-zain', name: 'Zain Tahir', avatar: 'assets/avatar-zain.png', role: 'listener', muted: true, speaking: false, vipTier: 'Glow' },
    ],
    capacity: 24,
    live: true,
    locked: false,
    giftsReceived: 2110,
    raisedHands: [],
    messages: [
      { id: 'rm-4', userId: 'user-maya', name: 'Maya Riaz', body: 'Beat Tap opens every 10 minutes.', time: ago(31), kind: 'system' },
      { id: 'rm-5', userId: 'user-ray', name: 'Ray Malik', body: 'Top score gets a bonus gift.', time: ago(11), kind: 'chat' },
    ],
    startedAt: ago(44),
  },
  {
    id: 'room-focus',
    title: 'Focus Circle',
    topic: 'Study',
    language: 'Urdu / English',
    hostId: 'user-noor',
    hostName: 'Noor Fatima',
    cover: 'assets/room-garden.png',
    mood: 'Calm',
    description: 'Silent sprints, mic check-ins, and study accountability.',
    tags: ['Study', 'Wellness', 'Focus'],
    participants: [
      { userId: 'user-noor', name: 'Noor Fatima', avatar: 'assets/avatar-noor.png', role: 'host', muted: false, speaking: false, vipTier: 'Free' },
      { userId: 'user-zain', name: 'Zain Tahir', avatar: 'assets/avatar-zain.png', role: 'listener', muted: true, speaking: false, vipTier: 'Glow' },
      { userId: 'user-ali', name: 'Ali Khan', avatar: 'assets/avatar-ali.png', role: 'listener', muted: true, speaking: false, vipTier: 'Free' },
    ],
    capacity: 12,
    live: true,
    locked: false,
    giftsReceived: 960,
    raisedHands: [],
    messages: [
      { id: 'rm-6', userId: 'user-noor', name: 'Noor Fatima', body: 'Next 25-minute focus sprint starts now.', time: ago(6), kind: 'system' },
    ],
    startedAt: ago(28),
  },
];

const seedTransactions: Transaction[] = [
  { id: 'tx-1', type: 'purchase', amount: 1500, method: 'JazzCash', status: 'completed', detail: 'Demo top-up package', time: ago(1440) },
  { id: 'tx-2', type: 'gift', amount: -140, method: 'Room Gift', status: 'completed', detail: 'Rose Beat sent in Afterglow Lounge', time: ago(110) },
  { id: 'tx-3', type: 'earning', amount: 72, method: 'Host Reward', status: 'completed', detail: 'Gift reward from Pulse Arcade', time: ago(72) },
  { id: 'tx-4', type: 'vip', amount: -899, method: 'VIP Upgrade', status: 'completed', detail: 'Glow membership activated', time: ago(60) },
];

const seedNotifications: NotificationItem[] = [
  { id: 'nt-1', type: 'message', title: 'New private message', body: 'Sana invited you to Afterglow Lounge.', time: ago(10), read: false },
  { id: 'nt-2', type: 'follower', title: 'New follower', body: 'Maya Riaz followed your profile.', time: ago(38), read: false },
  { id: 'nt-3', type: 'invite', title: 'Room invite', body: 'Ray Malik wants you in Pulse Arcade.', time: ago(75), read: true },
  { id: 'nt-4', type: 'system', title: 'Safety reminder', body: 'Hosts can remove disruptive rooms from the admin panel.', time: ago(180), read: true },
];

const vipPlans: VipPlan[] = [
  {
    id: 'Glow',
    price: 899,
    spotlight: 'For active listeners',
    accent: '#3bebc2',
    benefits: ['Glow badge', 'Priority room row', 'Monthly bonus coins', 'Animated profile ring'],
  },
  {
    id: 'Prime',
    price: 1899,
    spotlight: 'For serious hosts',
    accent: '#ffd561',
    benefits: ['Prime badge', 'Featured host slot', 'Larger room capacity', 'Gift multiplier boost'],
  },
  {
    id: 'Legend',
    price: 3499,
    spotlight: 'For platform stars',
    accent: '#ff6e62',
    benefits: ['Legend badge', 'Top search visibility', 'Exclusive room theme', 'Dedicated support queue'],
  },
];

export const createInitialState = (): AppState => ({
  sessionUserId: 'user-zain',
  users: seedUsers,
  rooms: seedRooms,
  threads: [
    {
      id: 'thread-sana',
      userId: 'user-sana',
      userName: 'Sana Mir',
      avatar: 'assets/avatar-sana.png',
      lastMessage: 'Join Afterglow when you are free.',
      unread: 1,
      messages: [
        { id: 'dm-1', from: 'user-sana', body: 'Join Afterglow when you are free.', time: ago(13) },
        { id: 'dm-2', from: 'user-zain', body: 'On my way. Save me a speaker seat.', time: ago(8) },
      ],
    },
    {
      id: 'thread-ray',
      userId: 'user-ray',
      userName: 'Ray Malik',
      avatar: 'assets/avatar-ray.png',
      lastMessage: 'Beat Tap leaderboard is getting wild.',
      unread: 0,
      messages: [
        { id: 'dm-3', from: 'user-ray', body: 'Beat Tap leaderboard is getting wild.', time: ago(32) },
      ],
    },
  ],
  gifts: seedGifts,
  transactions: seedTransactions,
  notifications: seedNotifications,
  announcements: [
    { id: 'an-1', type: 'system', title: 'Welcome to Voxora', body: 'All core demo modules are ready to explore.', time: now(), read: false },
  ],
  vipPlans,
  gameStats: {
    beatTapBest: 18,
    spinWins: 2,
    dailyStreak: 4,
  },
});
